### ISSUE TITLE
Upgrade model convert functions

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#3]
As seen in 0a4ece7ed77afa16a057a992cccc3db9f4a5bf41 for just the Group model, ext-5.1 introduces a new config option for fields called `depends` that works in conjunction with `convert` to ensure that convert functions get run in the right order and can use other fields consistently.

Search the models and stores folders for `convert`, update their syntax for accessing other fields, and ensure the depends array is complete and accurate.

**Comment by BillClinton** [comment]
This should be fixed by https://github.com/SlateFoundation/slate-admin/commit/ae5963596e46fbcd6f0b5780a2ddbd31db427cab

a search of the models directories found only four instances of the "convert" attribute.  Two of these were already addressed in https://github.com/SlateFoundation/slate-admin/commit/0a4ece7ed77afa16a057a992cccc3db9f4a5bf41

**Comment by themightychris** [comment]
looks good
