### ISSUE TITLE
Loading all users not possible

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-admin#31]
There is no way to load all users. Searching with no search criteria does not bring up this list and only groups can be brought up, but without the full list, you can't assign them to that group.

**Comment by themightychris** [comment]
This was intentional as the list of full students can be quite large and we didn't want people getting stalled up waiting for it to load when they just want to click through to a deeper group, but it does make things awkward when you are getting started and I agree it would be better if we did allow loading the whole population. Experienced users that want to skip the wait could learn to just hit the arrow to expand it without loading the full list

**Comment by themightychris** [comment]
Let's open up a route for loading all users and allow clicking the "All students" item in the tree trigger it like the groups below do

**Comment by themightychris** [comment]
@BillClinton kicking back to you for branch to be rebased onto development, reassign to me when it's ready. Also be sure to check the comments i left in the old PR #37

**Comment by BillClinton** [comment]
@chris this branch has been rebased and named  features/allusers-31 . I responded to comments in PR, but we should probably discuss more.  Awaiting your response

**Comment by BillClinton** [comment]
@themightychris this checks out in development branch and is ready for Q&A and/or closure

**Comment by ckunkel** [comment]
This issue
