### ISSUE TITLE
Tree expanders missing after update to new slate theme

### ISSUE THREAD

**Issue by BillClinton** [SlateFoundation/slate-admin#46]
The expanders for rows in the tree panels are no longer visible and branch nodes cannot be expanded.  This behavior exists in the People nav panel, in groups settings and in terms settings.   This can be seen in the development branch.

**Comment by ryon** [comment]
@BillClinton @themightychris The lack of expander arrows is an intentional part of Ali's design. I was hoping the behavior of the tree items could be tweaked for better usability; right now you can use the keyboard (right arrow) or double-clicking to expand (this latter options seems finicky).

**Comment by ryon** [comment]
@themightychris What is left to do for this?

**Comment by themightychris** [comment]
@ryon see SlateFoundation/slate-theme#5

I know hiding them was intentional, but I want it to be opt-in with a supplemental class rather than being blanketed across all tree grids. Without them the trees are unusable without supplemental behavior layered on top. Where we layer in that supplemental behavior we can add this class to remove the expanders. Currently though I don't see a viable/desirable way to globally alter all treegrids, so when we need treegrids in other places they need to be able to function stock at least until we can enhance them and add the class

**Comment by themightychris** [comment]
@ryon also now that they're back I think i prefer the people search filter group tree having the expanders as they provide powerusers a way to dive down to a specific group without triggering a load of all people now that we allow that

**Comment by ryon** [comment]
@themightychris New custom SVG expanders are in via:

- https://github.com/SlateFoundation/slate-theme/commit/fd4f2b13c1b17b471deea2b819db487cb7619bc3
- https://github.com/SlateFoundation/slate-theme/commit/07f8b022af3f6a07ac1fe180fe3364f05baf1c6c
- https://github.com/SlateFoundation/slate-admin/commit/6b2d40e0894ae1e4c748dd0330c802e8244c382d
